# Generated by Django 4.1.2 on 2022-10-31 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 17, 1, 45, 179504)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='note_label',
            field=models.CharField(choices=[('P', 'primary'), ('SE', 'secondary'), ('SU', 'success'), ('D', 'danger'), ('W', 'warning'), ('I', 'info'), ('L', 'light'), ('D', 'dark')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
